/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.bsi.sismed.view;

import br.edu.ifpr.bsi.sismed.bean.Estado;
import br.edu.ifpr.bsi.sismed.dao.EstadoDAO;
import br.edu.ifpr.bsi.sismed.view.FormEstado;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alisson
 */
public class FormEstadoPrincipal extends javax.swing.JFrame {

    List<Estado> listaEstados = new ArrayList<Estado>();
    public FormEstadoPrincipal() {
        initComponents();
        atualizaTabela();
        jbtEditar.setEnabled(false);
        jBTExcluir.setEnabled(false);
    }
    private void atualizaTabela() {

         try {
             listaEstados = EstadoDAO.pesquisar(retornaObjeto());
        
         DefaultTableModel modelo = (DefaultTableModel) jTBEstado.getModel();
         modelo.setNumRows(0);
         for (Estado estado : listaEstados) {
             modelo.addRow(new Object[]{
                 estado.getNomeEstado(),
                 estado.getSiglaEstado()
             });
         }
          } catch (SQLException ex) {
             System.out.println("Dados não disponíveis.");
         }
    }

    private Estado retornaObjeto() {
        Estado e = new Estado();
        e.setNomeEstado(jTFEstado.getText().toUpperCase());
        return e;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estadoDAO1 = new br.edu.ifpr.bsi.sismed.dao.EstadoDAO();
        jLabel1 = new javax.swing.JLabel();
        jTFEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBEstado = new javax.swing.JTable();
        jbtEditar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBTPesquisar = new javax.swing.JButton();
        jBTSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estado");

        jTFEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFEstadoKeyTyped(evt);
            }
        });

        jTBEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Estado", "UF"
            }
        ));
        jTBEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBEstadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTBEstado);

        jbtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sismed/icones/BotaoEditar.png"))); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });

        jBTExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sismed/icones/delete.png"))); // NOI18N
        jBTExcluir.setText("Excluir");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sismed/icones/BotaoNovo.png"))); // NOI18N
        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBTPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sismed/icones/LupaPesquisar.png"))); // NOI18N
        jBTPesquisar.setText("Pesquisar");
        jBTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTPesquisarActionPerformed(evt);
            }
        });

        jBTSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sismed/icones/excluir.png"))); // NOI18N
        jBTSair.setText("Sair");
        jBTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(41, 41, 41)
                        .addComponent(jbtEditar)
                        .addGap(61, 61, 61)
                        .addComponent(jBTExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBTSair))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtEditar)
                    .addComponent(jBTExcluir)
                    .addComponent(jButton3)
                    .addComponent(jBTSair))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTPesquisarActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_jBTPesquisarActionPerformed

    private void jTFEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEstadoKeyTyped
        atualizaTabela();
    }//GEN-LAST:event_jTFEstadoKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new FormEstado().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBTSairActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        
        Estado estado = listaEstados.get(jTBEstado.getSelectedRow());
        new FormEstado(estado).setVisible(true);
        
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jTBEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBEstadoMouseClicked
        jbtEditar.setEnabled(true);
        jBTExcluir.setEnabled(true);
    }//GEN-LAST:event_jTBEstadoMouseClicked

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        Estado estado = listaEstados.get(jTBEstado.getSelectedRow());
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que quer exluir esse estado?");
        if(opcao == JOptionPane.YES_OPTION){
            try{
                EstadoDAO.excluir(estado);
                atualizaTabela();
            } catch (SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jBTExcluirActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEstadoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEstadoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEstadoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEstadoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEstadoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.edu.ifpr.bsi.sismed.dao.EstadoDAO estadoDAO1;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTPesquisar;
    private javax.swing.JButton jBTSair;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBEstado;
    private javax.swing.JTextField jTFEstado;
    private javax.swing.JButton jbtEditar;
    // End of variables declaration//GEN-END:variables
}
